# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


parameters:
- name: BucketOrigen
  type: string

- name: BucketDestino
  type: string

variables:
- group: DEV-ENV


pool:
  vmImage: ubuntu-latest

jobs:
- job: first_job
  displayName:  the first job
  steps:
  - script: echo Hello, world!  $(role-asumme-dev)
    displayName: 'Run a one-line script'

  - script: |
      echo "el primer bucket origen es: ${{ parameters.Bucket-Origen }}"
      echo "el primer bucket origen es: ${{ parameters.Bucket-Destino }}"
    displayName: 'Migracion de buckets'
