
name: CI

on:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Este es el pipeline miooooo ejeutandose en DEVVVVVV!"

